name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash

env:
  RUSTFLAGS: --deny warnings

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust Toolchain Components
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: Swatinem/rust-cache@v2

    - name: Test
      run: cargo test --all

  Integration:                  # 1 job for each Bitcoin Core version.
    name: Integration tests - stable toolchain
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bitcoinversion:
          [
            "0.18.0",
            "0.18.1",
            "0.19.0.1",
            "0.19.1",
            "0.20.0",
            "0.20.1",
            "0.21.0",
          ]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Select toolchain"
        uses: dtolnay/rust-toolchain@stable
      - name: "Run integration tests"
        env:
          BITCOINVERSION: ${{ matrix.bitcoinversion }}
        run: ./contrib/integration_test.sh
